### ISSUE TITLE
Blueprint test should error if targeting an undefined stage

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#1000]
Right now it's easy to target the wrong stage. If the environment variable is set to a non-existent stage, we should error out.

We should also consider aliasing some of the old stage names:
- converge -> apply
- setup -> init

**Comment by bharathkkb** [comment]
fixed with old stage mappings in CLI
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/9353691e4d74c65d2226d66c3ebe7f91e9673d6b/cli/bptest/stages.go#L5-L12
