### ISSUE TITLE
Complex outputs from TFT blueprint tests

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1002]
For some test cases we may need complex outputs from a blueprint test. We currently support [GetStringOutput](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/39b4ef08bb23b352ea6ff7073f942ec0b5a50fc7/infra/blueprint-test/pkg/tft/terraform.go#L204) however we may require others like [OutputList](https://pkg.go.dev/github.com/gruntwork-io/terratest@v0.37.12/modules/terraform#OutputList), OutputMap etc. We should either export the `getTFOptions` from tft package and directly enable usage of terratest or create wrappers for common output types.

**Comment by morgante** [comment]
We should export `getTFOptions` to avoid wrapping every terratest function.
