### ISSUE TITLE
Scorecard: New error generating violations 

### ISSUE THREAD

**Issue by husseyd** [GoogleCloudPlatform/cloud-foundation-toolkit#1009]
CFT Scorecard is generating a new error on the daily scheduled scan we run. There are no relevant changes to our infrastructure or usage of the CLI tool. Have repeated the pipeline and tweaked a little bit still get this result.

Could a change in GCP's CAI output format be responsible?

Resource names are redacted.

```
cft scorecard --workers 2 --policy-path policy-library/ --dir-path output/cai-dump/ --output-path output/cft-report/
Generating CFT scorecard
Error: Fetching inventory from local directory: converting asset {"name":"//pubsub.googleapis.com/projects/{{PROJECT}}/topics/{{PUBSUB_TOPCI}}","asset_type":"pubsub.googleapis.com/Topic","iam_policy":{"etag":"{{ETAG}}","bindings":[{"role":"roles/pubsub.publisher","members":["serviceAccount:{{SA_NAME}@{{PROJECT}}.iam.gserviceaccount.com"]}]},"ancestors":["projects/{{PROJECT_NUM}}","folders/{{FOLDER_ID}}","folders/{{FOLDER_ID}}","folders/{{FOLDER_ID}}","organizations/{{ORD_ID}}"],"update_time":"2021-09-09T04:04:09.586830Z"} to proto: unmarshaling to proto: illegal base64 data at input byte 7
```

**Comment by morgante** [comment]
Can you share a minimal CAI dump which reproduces this error?

**Comment by husseyd** [comment]
Got something. It's coming from the iam_inventory.json file, specifically etags on IAM policies. I've observed this happening with PubSub topics IAM policies and also GCS IAM policies

Here's an example that triggers the error, with everything redacted except the etag. Pop this in the `iam_inventory.json` file. All other files can be left empty for the test (normally we would run it with resource_inventory etc as well).

```
{"name":"//pubsub.googleapis.com/projects/project-name/topics/top-sub-top","asset_type":"pubsub.googleapis.com/Topic","iam_policy":{"etag":"BwXLiBc_lI4=","bindings":[{"role":"roles/pubsub.publisher","members":["serviceAccount:sa-pubsub-aaaa-bbbb@project-name.iam.gserviceaccount.com"]}]},"ancestors":["projects/1234411661234","folders/123479721234","folders/123499561234","folders/123460761234","organizations/123449281234"],"update_time":"2021-09-09T04:04:09.586830Z"}
```

If you replace the `etag` field with `aaaaaaaa` it runs fine... Maybe CFT Scorecard is trying to un-base64 the etag field when it shouldn't be.

**Comment by husseyd** [comment]
Good thinking - could be similar issue of pre-stripped padding
https://stackoverflow.com/a/42683706

**Comment by hussainak** [comment]
> I've done a bit of investigation internally and it seems that CAI [recently changed](https://cloud.google.com/asset-inventory/docs/release-notes) their code to export "web-safe" base64-encoded values. (To confirm, I suspect that if you replace the `_` with `+` it will work.)
> 
> One possible fix is trying to upgrade our old/deprecated version of the proto package. Upgrading to the [new package](https://pkg.go.dev/google.golang.org/protobuf/proto) might be a possible fix.
> 
> Unfortunately beyond that this might be a problem with the various API protos not also using web-safe formatting. Could either of you file a support case and have it CCed to me ([morgantep@google.com](mailto:morgantep@google.com))? That will help with escalating internally.

I am unsure if upgrading the module packages will work. Still showing up the same illegal base64 data error. 
My go.mod is 
`module github.com/GoogleCloudPlatform/cloud-foundation-toolkit/cli

go 1.12

require (
	cloud.google.com/go/asset v1.0.1
	cloud.google.com/go/storage v1.18.2
	github.com/GoogleCloudPlatform/config-validator v0.0.0-20210826195402-2f28ba6ec9ac
	github.com/briandowns/spinner v1.16.0
	github.com/gammazero/workerpool v1.1.2
	github.com/golang/protobuf v1.5.2
	github.com/google/go-cmp v0.5.6
	github.com/inconshreveable/log15 v0.0.0-20201112154412-8562bdadbbac
	github.com/open-policy-agent/opa v0.33.1
	github.com/pkg/errors v0.9.1
	github.com/spf13/cobra v1.2.1
	github.com/spf13/viper v1.9.0
	github.com/stretchr/testify v1.7.0
	google.golang.org/genproto v0.0.0-20211021150943-2b146023228c
	gopkg.in/yaml.v2 v2.4.0
	gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
)`

**Comment by morgante** [comment]
I have released the workaround as `v0.4.1`.

I also started looking at upgrading the protobuf library as I *do* think that will fix the issue, based on the fact that our internal version has been upgraded and doesn't have this same problem. Here's my start to that: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1016

However, this is likely to be a fairly involved migration as it looks like we also need to upgrade the core Config Validator proto packages at the same time.

**Comment by hussainak** [comment]
@morgante looks like v0.4.1 wasn't released yet due to some error during the build process. In relation to protobuf I have given that a shot already and looks like you'd need to do more for a fix.

**Comment by morgante** [comment]
@hussainak It's in the GCS bucket.

**Comment by hussainak** [comment]
Thanks @morgante, could you please give the GCS url... it would be helpful to have it under Releases as an https URL though.

**Comment by morgante** [comment]
The link depends on your platform:
```
# OS X
curl -o cft https://storage.googleapis.com/cft-cli/latest/cft-darwin-amd64
# Linux
curl -o cft https://storage.googleapis.com/cft-cli/latest/cft-linux-amd64
# executable
chmod +x cft

# Windows
curl -o cft.exe https://storage.googleapis.com/cft-cli/latest/cft-windows-amd64
```

We do hope to get the release pipeline working again soon. /cc @bharathkkb

**Comment by hussainak** [comment]
Sure thanks, we will wait for @bharathkkb to fix pipeline permissions and do the release.
