### ISSUE TITLE
Issue in importing attached disks in order from gce using terraform

### ISSUE THREAD

**Issue by nikhil12045** [GoogleCloudPlatform/cloud-foundation-toolkit#1020]
I am importing a GCE instance with 3 attached disks that are already deployed using terraform. The problem is , when I import , the attached disks are not in order(saw in state file). This is creating conflict with the main file when working with multiple resources. Is there a way to import resource(attached disks in instance) in particular order. Or any other suggestion.

Here the statefile:

            "attached_disk": [
          {
            "device_name": "disk01",
            "disk_encryption_key_raw": "",
            "disk_encryption_key_sha256": "",
            "kms_key_self_link": "",
            "mode": "READ_WRITE",
            "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxxxxxxxxxxxxxx/disk01"
          },
          {
            "device_name": "disk03",
            "disk_encryption_key_raw": "",
            "disk_encryption_key_sha256": "",
            "kms_key_self_link": "",
            "mode": "READ_WRITE",
            "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxxxxxxxxxxxxxxxxx/disk03"
          },
          {
            "device_name": "disk02",
            "disk_encryption_key_raw": "",
            "disk_encryption_key_sha256": "",
            "kms_key_self_link": "",
            "mode": "READ_WRITE",
            "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxxxxxxxxxxx/disk02"
          }
        ]
But I want something like this

            "attached_disk": [
          {
            "device_name": "disk01",
            "disk_encryption_key_raw": "",
            "disk_encryption_key_sha256": "",
            "kms_key_self_link": "",
            "mode": "READ_WRITE",
            "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxxxxxxxxxxxxxx/disk01"
          },
          {
            "device_name": "disk02",
            "disk_encryption_key_raw": "",
            "disk_encryption_key_sha256": "",
            "kms_key_self_link": "",
            "mode": "READ_WRITE",
            "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxxxxxxxxxxxxxxxxx/disk02"
          },
          {
            "device_name": "disk03",
            "disk_encryption_key_raw": "",
            "disk_encryption_key_sha256": "",
            "kms_key_self_link": "",
            "mode": "READ_WRITE",
            "source": "https://www.googleapis.com/compute/v1/projects/xxxxxxxxxxxxxxxxxxx/disk03"
          }
        ]
The import command used is as:

terraform import google_compute_instance.instance_name project/**************/instance_name

**Comment by morgante** [comment]
This isn't the right repo to report Terraform issues. Issues with the Terraform provider can be reported here: https://github.com/hashicorp/terraform-provider-google/issues
