### ISSUE TITLE
Allow for Backend Terraform Configuration when using Developer Tools CLI Image

### ISSUE THREAD

**Issue by mattkizaric-leveragelab** [GoogleCloudPlatform/cloud-foundation-toolkit#1034]
Hello,

My team is using the [Developer Tools Image](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/infra/build/developer-tools) for local development of new modules. To isolate our development environments, we create a new gcp project and use that project to test and verify the infrastructure.

However, it has been a pain that we cannot configure the backend bucket or prefix when using the docker image. I believe it would be a relatively easy change to include these as configuration options while running the [prepare_environment](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/scripts/task_helper_functions.sh#L479) function.

We would like to be able to configure the backend bucket by defining an optional environment variable that could be used in the `terraform init` function:

TF_BACKEND_CONFIG_FILE
- A bucket id to use while configuring the backend

I believe these could be added with a change to [task_helper_functions.sh](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/scripts/task_helper_functions.sh#L485):
```
   if [[ -e "${TF_BACKEND_CONFIG_FILE}" ]] then
    terraform init -backend-config="${TF_BACKEND_CONFIG_FILE}"
  else
    terraform init
  fi
```
A similar if statement would need to be added to [cleanup_environment](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/scripts/task_helper_functions.sh#L495)

Let me know if this is something we should submit a PR for or if it can be rolled up into one of the open PRs. Thanks.

**Comment by bharathkkb** [comment]
Hi @mattkizaric-leveragelab 
> To isolate our development environments, we create a new gcp project and use that project to test and verify the infrastructure

We also follow a similar pattern. In this case whats the use case of having remote state rather locally on the dev machine. 

We could look into adding this but I wanted to understand the use-case better.

**Comment by mattkizaric-leveragelab** [comment]
> Hi @mattkizaric-leveragelab
> 
> > To isolate our development environments, we create a new gcp project and use that project to test and verify the infrastructure
> 
> We also follow a similar pattern. In this case whats the use case of having remote state rather locally on the dev machine.
> 
> We could look into adding this but I wanted to understand the use-case better.

We often use this flow in our CI/CD pipeline with code reviews, so it is helpful to be able to have a remote state that is updated as new commits are added to a PR. 

Workflow:
1. Local development is done, the ephemeral project is set up locally and tests are run on a developers machine. Often our projects are named after the git branch the developer is using (JIRA-1234)
2. Developer Pushes to remote branch and/or opens a PR. Tests should be re-run automatically using our CI/CD pipeline on any new commits.
3. After checks pass, the PR is merged into our main branch. The ephemeral project is destroyed and all resources are deleted.

**Comment by morgante** [comment]
What if we passed through [`TF_CLI_ARGS`](https://www.terraform.io/docs/cli/config/environment-variables.html#tf_cli_args-and-tf_cli_args_name)? This would allow you to set the backend config without us explicitly adding code for that workflow.

**Comment by bharathkkb** [comment]
TIL and it works! You will need to use `TF_CLI_ARGS_init` as  just`TF_CLI_ARGS` will error out for the subsequent apply as it affects all commands.

**Comment by mattkizaric-leveragelab** [comment]
Thank you @morgante and @bharathkkb. That seems to do the trick. Appreciate the help!
