### ISSUE TITLE
developer-tools:1.2.4 docker fails executing kitchen commands

### ISSUE THREAD

**Issue by rohvarsh** [GoogleCloudPlatform/cloud-foundation-toolkit#1037]
Kitchen commands are failing in developer-tools images starting version 1.2.4. It's working fine till version 1.2.3.

**Error Logs:**

Preparing the "docker+machine" executor
Using Docker executor with image gcr.io/cloud-foundation-cicd/cft/developer-tools:1.2.4 ...
Pulling docker image gcr.io/cloud-foundation-cicd/cft/developer-tools:1.2.4 ...
Using docker image sha256:0eb183545244ca6c11c422be2b6382cb05a626d7c3f6a90bfad8914133e4a02d for gcr.io/cloud-foundation-cicd/cft/developer-tools:1.2.4 with digest gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:f3ed03bbe8714fa99c4e630977b11921bb24542293014680f098474981129448 ...
Preparing environment
Running on runner-nthfetyx-project-32324287-concurrent-0 via runner-nthfetyx-shared-1640202328-570615ec...
Getting source from Git repository
$ eval "$CI_PRE_CLONE_SCRIPT"
Fetching changes with git depth set to 50...
Initialized empty Git repository in /builds/cynergyfusion/engineering-team/iac/tf-modules/tf-mod-gcp-gcs/.git/
Created fresh repository.
Checking out f9dfb35a as CYNERGY-22566...
Skipping Git submodules setup
Executing "step_script" stage of the job script
Using docker image sha256:0eb183545244ca6c11c422be2b6382cb05a626d7c3f6a90bfad8914133e4a02d for gcr.io/cloud-foundation-cicd/cft/developer-tools:1.2.4 with digest gcr.io/cloud-foundation-cicd/cft/developer-tools@sha256:f3ed03bbe8714fa99c4e630977b11921bb24542293014680f098474981129448 ...
$ mv test/fixtures/tf_module/example.tfvars test/fixtures/tf_module/terraform.tfvars
$ kitchen converge
-----> Starting Test Kitchen (v2.7.2)
-----> Creating <kt-suite-gcp>...
$$$$$$ Reading the Terraform client version...
       Terraform v1.1.0
       on linux_amd64
       
       Your version of Terraform is out of date! The latest version
       is 1.1.2. You can update by downloading from https://www.terraform.io/downloads.html
$$$$$$ Finished reading the Terraform client version.
$$$$$$ Verifying the Terraform client version is in the supported interval of >= 0.11.4, < 1.1.0...
**>>>>>> Verifying the Terraform client version failed. Set `driver.verify_version: false` to downgrade this error to a warning.**
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <kt-suite-gcp>.  Please see .kitchen/logs/kt-suite-gcp.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

**Comment by rohvarsh** [comment]
@bharathkkb if possible, please have a look.

**Comment by bharathkkb** [comment]
Hi @rohvarsh 
v1.2.4 (https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/994) bumped Terraform version to `1.1.0`. It looks like kitchen requires TF to be `>= 0.11.4, < 1.1.0` https://github.com/newcontext-oss/kitchen-terraform/issues/467

You can get around this by specifying `driver.verify_version: false` as mentioned in the error message you posted above. Example:  https://github.com/terraform-google-modules/terraform-google-folders/blob/38c6281513746a81721c7cc3acaa91fa7c842155/kitchen.yml#L18
