### ISSUE TITLE
Type iamMemberBinding for  gcp-types/ gcp-types/compute-v1 

### ISSUE THREAD

**Issue by rubber-ant** [GoogleCloudPlatform/cloud-foundation-toolkit#1055]
Hi Team,

Is there any plan to implement for DM a new Type `iamMemberBinding` for  `gcp-types/ gcp-types/compute-v1` ?

I can see in Terraform is ready to use https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance_iam

Do you suggest switching from DM to Terraform?

Thanks a lot

**Comment by bharathkkb** [comment]
Hi @rubber-ant,
Yes we would recommend switching to Terraform
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm#dear-cft-user
