### ISSUE TITLE
blueprint test: Remove polling steps for krmt

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1060]
With beta.12 kpt live apply/destroy polls to completion by default and now waits forever for reconciliation. We should add a sane `--reconcile-timeout` to this and remove the `live status` based polling.

**Comment by apeabody** [comment]
@bharathkkb - Let me know if you think this is still relevant, I haven't seen any issues since https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/commit/36134916e2fd859b0aea4384c1b4a5ab79d65eac
