### ISSUE TITLE
lint test: discover and fail for unused variables 

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1093]
For cases like https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/issues/1168 we can catch these at lint time - for example https://github.com/terraform-linters/tflint/blob/master/docs/rules/terraform_unused_declarations.md

**Comment by morgante** [comment]
Could we integrate tflint as a whole? It would be helpful to have easy access to linting rules without having to do it on each repo.

**Comment by bharathkkb** [comment]
Yes, I was thinking of just integrating and maintaining common ruleset in devtools
