### ISSUE TITLE
Devtools image release is failing

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#1095]
Ex. https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/actions/runs/1955719423

**Comment by bharathkkb** [comment]
This seems to be due a gcloud issue with 376 - https://github.com/GoogleCloudPlatform/cloud-sdk-docker/issues/267. Gcloud team is also looking into this. We can temporarily pin gcloud to 375 to unblock builds.
