### ISSUE TITLE
devtools: update tooling failing due to porch release

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1116]
[Porch releases ](https://api.github.com/repos/GoogleContainerTools/kpt/releases)are tagged and release as `porch/v0.0.1 ` from kpt repo causing our update workflow to fail which expects vM.m.p. We should add some logic to handle this.

**Comment by apeabody** [comment]
Both porch and lpt use vM.m.p, however we can exclude porch releases as those are prefixed `porch/`.
