### ISSUE TITLE
Add support for skipping integration test based on change directory 

### ISSUE THREAD

**Issue by Shabirmean** [GoogleCloudPlatform/cloud-foundation-toolkit#1119]
#### Description
- The current configuration setup for CFT CI based repos doesn't check the files that were changed during the last commit; thus the pipeline is kicked off on every commit
- Ideally we would want to be able to specify that a certain CI pipeline/step should run only when changes are made to a specific subdirectory or file

#### Example:
- [anthos-samples](https://github.com/GoogleCloudPlatform/anthos-samples) repository uses the CI pipeline provided by CFT.
- With every change the [integration test steps](https://github.com/GoogleCloudPlatform/anthos-samples/blob/main/build/int.cloudbuild.yaml) in the cloudbuild yaml are run
- The integration tests are a time consuming affair and we would like to control when they are triggered based on what files are changed
- Ideally as repo owners we should be able to configure when to run a certain build steps in terms of folder changes

**EDIT**
- Directories that need to be included in the integration tests are:
   - `<REPO_ROOT>/anthos-bm-gcp-terraform`

**Comment by morgante** [comment]
At first I was thinking you could just do this in Cloud Build, but it would require many different triggers for parts of the repo so I do think adding this to the CLI could improve UX.

How about we add it to the `BlueprintTest` yaml. For example:

```
apiVersion: blueprints.cloud.google.com/v1alpha1
kind: BlueprintTest
metadata:
  name: quuz
spec:
  when:
  - changed:
     - "directory/regex/(.+)"
```

@Shabirmean Would that work for you?

**Comment by Shabirmean** [comment]
@morgante - I am not fully aware of how this becomes part of the CI pipeline. But this looks like something that can work. Ideally, this would be something that repo owners can place in their repos and have control of, instead of having to open a change with the Blueprints team.

**Comment by morgante** [comment]
Yes, that is a yaml file you place in your repo.

**Comment by bharathkkb** [comment]
@morgante WDYT about leveraging [included_files](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/cloudbuild_trigger#included_files) as a solution until we add this to the CLI. We can store a map of repo_name => included_file list and set that during t[rigger creation](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/8383c92c8a54322eebca8a058550b46396f043aa/infra/terraform/test-org/ci-triggers/triggers.tf#L33-L54) if a value exists in map. This would still be managed in this repo.

**Comment by morgante** [comment]
@bharathkkb Wouldn't that still require creating many triggers for a particular repo? It could work as a workaround, but you'd probably want to make it a map of lists `repo_name => [included_files_1, included_files_2]` where a separate trigger is created for each included files list.

**Comment by bharathkkb** [comment]
@morgante I believe the provider accepts a list input for `included_files` so we can pass in the list directly to a single trigger resource.
https://github.com/hashicorp/terraform-provider-google/blob/b5b0438689c8a10fad804bdbc59ff45afa8aeb33/google/resource_cloudbuild_trigger.go#L838

**Comment by morgante** [comment]
> @morgante I believe the provider accepts a list input for `included_files` so we can pass in the list directly to a single trigger resource. https://github.com/hashicorp/terraform-provider-google/blob/b5b0438689c8a10fad804bdbc59ff45afa8aeb33/google/resource_cloudbuild_trigger.go#L838

That should work.
