### ISSUE TITLE
Please add retention examples to Deployment Manager GCS templates

### ISSUE THREAD

**Issue by ServerlessArchitect** [GoogleCloudPlatform/cloud-foundation-toolkit#1179]
I'd like to set up a retention policy for a GCS bucket to prevent premature deletion of files. I'd like to do so with Deployment Manager, but I've not been able to find any documentation or examples. There are plenty of examples of how to use Deployment Manager for lifecycle settings (to automatically delete old files) not for retention settings (to prevent file deletion).

Please, could you add some retention examples to [the samples](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/google/resource-snippets/storage-v1)?

**Comment by bharathkkb** [comment]
@ServerlessArchitect Could you open an issue on https://github.com/GoogleCloudPlatform/deploymentmanager-samples
