### ISSUE TITLE
blueprint-test/pkg/krmt broken with kpt v1.0.0-beta.16+

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/cloud-foundation-toolkit#1190]
kpt [v1.0.0-beta.16](https://github.com/GoogleContainerTools/kpt/releases/tag/v1.0.0-beta.16)+ no longer supports Unchanged status used by blueprint-test/pkg/krmt.

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/f5c2433232d7966085b238416a3a13438b6a0ce0/infra/blueprint-test/pkg/krmt/krm.go#L289

**Comment by apeabody** [comment]
@bharathkkb - WDYT about pinning KPT to [v1.0.0-beta.15](https://github.com/GoogleContainerTools/kpt/releases/tag/v1.0.0-beta.15) till this is resolved?

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/f5c2433232d7966085b238416a3a13438b6a0ce0/infra/build/Makefile#L30

**Comment by bharathkkb** [comment]
@apeabody sounds good to me. Also if this is breaking anything, you should be able to skip DefaultVerify.

**Comment by apeabody** [comment]
> @apeabody sounds good to me. Also if this is breaking anything, you should be able to skip DefaultVerify.

Thanks - Unfortunately all the krmt tests are impacted, so we can't just skip a few.
