### ISSUE TITLE
Relies on a personally manged docker image.

### ISSUE THREAD

**Issue by tmc** [GoogleCloudPlatform/cloud-foundation-toolkit#1193]
This shows that an important input to the image is managed by a personal dockerhub account: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/d9b14d2613bf2515a125a3070d2eff7902a4a1e3/infra/build/developer-tools-light/Dockerfile#L16

**Comment by bharathkkb** [comment]
Thanks for the report @tmc 
Yeah we could move away from this and download the correct TF version inline.
