### ISSUE TITLE
DM/nat_gateway refactoring

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#123]
Relevant templates: [dm/templates/route](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates/nat_gateway)

Main issue: [#47: DM templates refactoring: template and schema improvements](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/47)

Context: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/120#event-2418668661

**Comment by bohdanyurov-gl** [comment]
TODO list:
- Add version, links to docs
- Switch to using type provider
- Add support for cross-project resource creation
