### ISSUE TITLE
update go to 1.18

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1232]

**Comment by bharathkkb** [comment]
- [ ] Devtools
- [ ] CLI
- [ ] Test framework

**Comment by bharathkkb** [comment]
Test framework https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1373#pullrequestreview-1276194510
Dec tools https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/commit/762b7de7a2befb2867a282fe171501fd50041df5

**Comment by apeabody** [comment]
CLI https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/commit/f780264a9131be3acf81a74a7fcea84b3f7db10e
