### ISSUE TITLE
internal modules should be ignored by metadata

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1426]
Any internal module (i.e submodule without readme) should be skipped when looking for submodules to generate metadata.

Probably an additional validation here https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/a7dcc74192eb0787e2f9cf06e6e1f69636f05574/cli/bpmetadata/cmd.go#LL71C34-L71C34

**Comment by g-awmalik** [comment]
Resolved with #1428
