### ISSUE TITLE
Add header to centrally managed files (e.g. CODEOWNERS)

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/cloud-foundation-toolkit#1506]
FYI @bharathkkb

**Comment by bharathkkb** [comment]
Another option could be a header to all the files we manage centrally and how to update them in this repo. Linter sounds good too but I think we will anyway a way to differential in some way if we decide to implement opt out for centrally managed files.

**Comment by apeabody** [comment]
> Another option could be a header to all the files we manage centrally and how to update them in this repo. Linter sounds good too but I think we will anyway a way to differential in some way if we decide to implement opt out for centrally managed files.

Sounds good - a header won't actually stop the changes, but as the files are centrally managed it is very easy to implement in comparison.

**Comment by apeabody** [comment]
Completed in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1577
