### ISSUE TITLE
gcloud sdk vs cli

### ISSUE THREAD

**Issue by apeabody** [GoogleCloudPlatform/cloud-foundation-toolkit#1521]
Do we need the full gcloud SDK, or would just the CLI be fine?  https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blame/master/infra/build/developer-tools/build/install_cloud_sdk.sh#L19

https://cloud.google.com/sdk/docs/install#linux

Currently `install_cloud_sdk.sh` is the single largest layer in the dev-tools image.

**Comment by bharathkkb** [comment]
Both CLI and SDK seems to have nearly same size and CLI has a `google-cloud-sdk` dir, so I am not sure if there is a diff

**Comment by apeabody** [comment]
Yeah, less diff than I expected, but expanded cli is still about 2/3 of sdk.

google-cloud-cli 553M
google-cloud-sdk 758M

**Comment by apeabody** [comment]
closing out as this isn't a priority
