### ISSUE TITLE
Support optional periodic tests

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1545]
Allow authors to configure optional period tests for their solution repos. For lint we can likely inject a cron in GHA. For int we could orchestrate trigger exec via scheduler. We might need to brainstorm how we want failures to be surfaced back, maybe GH issues?

**Comment by apeabody** [comment]
> For lint we can likely inject a cron in GHA.

@bharathkkb - Do we want to do automatically for every repo, or expose as a bool in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/terraform/test-org/org/locals.tf#L57?

Something like `actions/github-script` can be used to open a issue for the linter.

**Comment by bharathkkb** [comment]
@apeabody I think we should add it as an optional bool but disabled by default. 

> Something like actions/github-script can be used to open a issue for the linter.

 I was thinking of a unified way for both lint and int failures. Maybe we can have another cron that runs from main ~1h after nightly cron and gets the github check status using  `actions/github-script`.
