### ISSUE TITLE
Generate a header in codeowners file so maintainers know where to make edits

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1574]
Similar to https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/65d01e40e94e6ee47f9c3f22e6f26accb8cf54cd/infra/terraform/modules/lint_file/lint.yaml.tftpl#L15-L16

**Comment by apeabody** [comment]
We should also tweak the template formating - current there is an extra space if groups, but no users, are included as owners.
