### ISSUE TITLE
EXCLUDE_LINT_DIRS doesn't get picked up by lint test (check_whitespaces)

### ISSUE THREAD

**Issue by balajismaniam** [GoogleCloudPlatform/cloud-foundation-toolkit#1634]
Refs:
https://github.com/GoogleCloudPlatform/terraform-ml-image-annotation-gcf/pull/11
https://github.com/GoogleCloudPlatform/terraform-ml-image-annotation-gcf/pull/11#issuecomment-1571075348

I have used EXCLUDE_LINT_DIRS to ignore src/frontend/public directory but the lint checks keep failing still.

**Comment by apeabody** [comment]
After investigation check_whitespaces doesn't use EXCLUDE_LINT_DIRS, so we've excluded all `ico` files: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1632

Note the Repo needs to be tracking dev-tools `1.12` or `1` for this change to take effect.
