### ISSUE TITLE
iam-policy template

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/cloud-foundation-toolkit#17]
Hi,

I would like to request a CFT template for https://cloud.google.com/resource-manager/reference/rest/v1/projects/setIamPolicy.

It is a non-trivial update as it involves updatemasks and policy etags. Our main use case is to ensure all possible audit logs are being generated.

Currently we implement it via custom template: https://github.com/GoogleCloudPlatform/healthcare/blob/master/deploy/templates/data_project.py#L539

cc @ocsig @morgante

**Comment by umairidris** [comment]
It seems like terraform has a single template for both iam member bindings and audit configs: https://www.terraform.io/docs/providers/google/d/google_iam_policy.html which seem simpler to use. So I wonder if the existing iam_member template could be expanded to support this use case.

**Comment by ocsig** [comment]
Currently we have IAM member binding for IAM roles on the project level here:
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates/iam_member

We are actively working on extending this for the folder, organization level as well as the support of organization policies. I will add audit log policies to the feature request.
