### ISSUE TITLE
cft test run --verbose displays sensitive terraform outputs

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/cloud-foundation-toolkit#1701]
### Issue summary

Exposure of sensitive terraform outputs in integration test build logs.

### Reproduction steps

When using `cft test run --verbose` terraform output is streamed to the terminal. This includes displaying sensitive outputs in plaintext. Without `--verbose`, terraform outputs are excluded and build logs are no longer useful for troubleshooting or tracking deployment progress. This can be observed in the [build logs](https://pantheon.corp.google.com/cloud-build/builds/215257c6-b002-4d01-b260-9597fb286984) for [dynamic-web-app #114](https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/pull/114)

### Proposal

Do not display sensitive terraform outputs on --verbose. This [discussion](https://discuss.hashicorp.com/t/how-to-show-sensitive-values/24076/4) points to the notion that `terraform output -json` was not intended to display values for human consumption, but meant for direct machine integration. Based on that, options include:

* Tracking terraform CLI intent and do not use `terraform output -json` in tool output, dropping `-json`
* Adopt something like the proposed `-insecure` flag that cft users could add on top of --verbose to see sensitive values

**Comment by bharathkkb** [comment]
We currently get outputs using terratest https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/2977570586dce0980932f4553c7a18a23cff4c46/infra/blueprint-test/pkg/tft/terraform.go#L279C22-L279C22

We may want to initially do some config inspection in the constructor to understand which outputs are sensitive. Then if a sensitive output is requested inject a discard logger replacing the default logger.

**Comment by grayside** [comment]
It would be nice to keep the non-sensitive outputs, given the case I am seeing is when the entire set of outputs is printed at once.
