### ISSUE TITLE
The default GKE initialClusterVersion

### ISSUE THREAD

**Issue by gruihuang** [GoogleCloudPlatform/cloud-foundation-toolkit#177]
The schema of the GKE DM template has a default initialClusterVersion value 1.9.7-gke.6.
Is it possible that we use "latest" instead of a specific number in that field, or we must update the value now and again.

**Comment by umairidris** [comment]
Note https://github.com/terraform-google-modules/terraform-google-kubernetes-engine uses "latest" as default for "kubernetes_version".
