### ISSUE TITLE
Lint pipelines does not fail in some cases

### ISSUE THREAD

**Issue by bharathkkb** [GoogleCloudPlatform/cloud-foundation-toolkit#1817]
A readme diff was [introduced](https://github.com/terraform-google-modules/terraform-google-vm/pull/329) but the workflow [run](https://github.com/terraform-google-modules/terraform-google-vm/actions/runs/6077732467/job/16487904128#step:4:329) reported diff but didn't fail the pipeline.

**Comment by bharathkkb** [comment]
Maybe fixed by https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/1484?

**Comment by apeabody** [comment]
Very likely as I believe the issue was introduced in `1.9` and that fix landed in `1.11.3`.  The repo is still on `1.10`: https://github.com/terraform-google-modules/terraform-google-vm/pull/304

**Comment by bharathkkb** [comment]
Havent seen this happen after fix above
