### ISSUE TITLE
Invalid renovate config causing dependency dashboard warnings

### ISSUE THREAD

**Issue by glasnt** [GoogleCloudPlatform/cloud-foundation-toolkit#2086]
https://github.com/GoogleCloudPlatform/terraform-dynamic-python-webapp/issues/17 shows this issue: 

```
## Repository problems

These problems occurred while renovating this repository. [View logs](https://developer.mend.io//github/GoogleCloudPlatform/terraform-dynamic-python-webapp).

 - WARN: File contents are invalid JSON but parse using JSON5. Support for this will be removed in a future release so please change to a support .json5 file name or ensure correct JSON syntax.
 - WARN: getNewValue error
```

### Syntax error

Mend.io logs shows it's the https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/terraform/test-org/github/resources/renovate.json#L44 line that has an extra comma, which is invalid JSON. 

### getNewValue error

Unsure if this error is from the base repo or CFT.

**Comment by apeabody** [comment]
Thanks @glasnt - Regardless I should get it sorted out.

**Comment by apeabody** [comment]
Reopened till we can triage the `getNewValue error`.
