### ISSUE TITLE
[DM] Backend_service update example according to schema validation

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#220]
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/f597508fd01b1ddf86f1e6a84f0dbc95836bbf6f/dm/templates/backend_service/examples/backend_service_regional.yaml#L23

`balancingMode` is required based on the new schema. Please update example accordingly.

**Comment by dsmithuk** [comment]
Could the updates specified here be checked against *internal* load balancer and therefore backendservice too. From my testing these examples simply don't work anymore.

**Comment by ocsig** [comment]
@dsmithuk Thank you for reporting the issue, I opened #451 to track the issue, we will fix it soon.
