### ISSUE TITLE
DM/gke out of date

### ISSUE THREAD

**Issue by abdennebi** [GoogleCloudPlatform/cloud-foundation-toolkit#247]
Hi,

I've tried to create a private cluster but the deprecated field [privateCluster](https://cloud.google.com/kubernetes-engine/docs/reference/rest/v1beta1/projects.locations.clusters#Cluster.FIELDS.private_cluster) is no more recongnized (I got error: field does not exist); although other deprecated fields are still recongnized.

So, I used the recommended way by using ``privateClusterConfig.enablePrivateNodes: true`` but my cluster nodes were still public. 

That's when I realized that the template ``gke.py`` were laking many fields (I presume that they are new), also other fields has been deprecated which is not documented into the schema. 

Some of the fields that are not present in ``gke.py``:

- ``nodePools``
- ``binaryAuthorization``
- ``autoscaling``
- ``networkConfig``
- ``defaultMaxPodsConstraint``
- ``resourceUsageExportConfig``
- ``authenticatorGroupsConfig``
- ``privateClusterConfig``
- ``verticalPodAutoscaling``
- ``shieldedNodes``
- ``workloadIdentityConfig``
- ``enableTpu``
- ``tpuIpv4CidrBlock``
- ``databaseEncryption``

I ended up using directly ``container.v1.cluster`` to create my cluster.

Design Question : even though this will be fixed, I thing we'll face the same problem in the future as GKE's API continues to evolve :

*Why not just stop hard code the optional properties?*

Regards,

**Comment by ocsig** [comment]
Sorry for the slow reply, this issue slipped under my radar. I believe the cft-dm-dev branch covers this. soon to be merged to master. #294

**Comment by ocsig** [comment]
The reason to "Hardcode" is to catch typos in the properties.
