### ISSUE TITLE
Documentation update needed

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#252]
Cloud Router>> network

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/d209b294f27f3218bc696834718df8f8cbdbbeec/dm/templates/network/network.py.schema#L53

**Comment by bohdanyurov-gl** [comment]
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/56

**Comment by morgante** [comment]
@bohdanyurov-gl This file still includes a number of "Cloud Router" references: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/cft-dm-dev/dm/templates/network/network.py.schema

**Comment by bohdanyurov-gl** [comment]
@morgante This issue is clear to me. I've simply added a reference to relevant ticket

**Comment by morgante** [comment]
@bohdanyurov-gl Got it, I wasn't sure if you were implying this was fixed in #56.
