### ISSUE TITLE
instance tests are failing

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#264]
templates/instance/tests/integration/instance.bats is failing:

> - code: CONDITION_NOT_MET
     location: /deployments/cft-test-workspace-221111-instance-9y9ef7rgu0/resources/test-instance-9y9ef7rgu0->$.properties
     message: '"/networkInterfaces/0/accessConfigs/0/natIP": domain: validation; keyword:
       type; message: instance does not match any allowed primitive type; allowed: ["string"];
       found: "null"'

Expanded config:
```
    - accessConfigs:
      - natIP: null
        type: ONE_TO_ONE_NAT
```

**Comment by sjvanrossum** [comment]
Fixed by PR#269.
