### ISSUE TITLE
Invalid example - Cloud build trigger

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#274]
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/10ab68c1680f61a3a1bfd929dbba760f216f952e/dm/templates/cloudbuild/examples/cloudbuild_trigger.yaml#L30

Property 'build' got renamed/moved in the schema, needs a fix.

**Comment by nick4fake** [comment]
@ocsig It was always build_template, probably example was wrong from the beginning

**Comment by nick4fake** [comment]
![image](https://user-images.githubusercontent.com/1065993/64531470-43b32300-d318-11e9-8b02-1873b194c0db.png)

Please note, that due to incorrect gcp-type mapping field "revision" is not supported
