### ISSUE TITLE
Remove outdated Forseti Deployment Sample

### ISSUE THREAD

**Issue by dekuhn** [GoogleCloudPlatform/cloud-foundation-toolkit#278]
Please remove this outdated Forseti Deployment Manager sample [here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/f8117cfe058dfcdb700ff4278fa576ee4223c549/dm/templates/forseti). The most up to date deployment instructions can be found on our website [forsetisecurity.org](https://forsetisecurity.org/docs/latest/setup/install.html) or in our Terraform github repo [terraform-google-forseti](https://github.com/forseti-security/terraform-google-forseti)

**Comment by morgante** [comment]
@ocsig Are you okay with this? I don't think it's used and the Forseti team don't want to maintain the DM-based installer.

**Comment by dekuhn** [comment]
The forseti folder appears to have been removed from master. Closing this issue. 

https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates/forseti - 404! :-)
