### ISSUE TITLE
Which repo is authoritative?

### ISSUE THREAD

**Issue by krismolendyke** [GoogleCloudPlatform/cloud-foundation-toolkit#279]
Which repository is the authoritative source for Cloud Foundation Toolkit and templates?  

I just discovered this one today after finding a comment on an issue https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/455#issuecomment-494966811 calling this the "new" repo.  It also mentions that the "old" repo (https://github.com/GoogleCloudPlatform/deploymentmanager-samples) will get updates from this upstream repo every few weeks.

However, some of the contents of the [templates dir](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates) is this repo is currently lagging behind [those in the other repo](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/tree/master/community/cloud-foundation/templates).  I'm particularly looking at the BQ templates.

Having the CFT exist in two places is confusing.  Can one be deprecated or removed?  Even a comment in a readme would go a long way toward getting folks to contribute to the correct repo, thanks.

**Comment by morgante** [comment]
This repo should be the authoritative source. I agree we should add a notice to the other one (and likely entirely remove the templates there entirely).

@ocsig Can you handle?
