### ISSUE TITLE
CloudSQL template doesn't allow to set IP address manually in private ip range

### ISSUE THREAD

**Issue by gdzieleziesz** [GoogleCloudPlatform/cloud-foundation-toolkit#289]
CloudSQL template cloud_sql.py doesn't allow to set IP address manually in private IP range as in below sample. 

ipAddresses:
- ipAddress: x.x.x.1
  type: PRIVATE

**Comment by ocsig** [comment]
Would you be able to give me a more detailed example about your usecase, maybe the API/Doc page which describes it?

**Comment by gdzieleziesz** [comment]
We had requirement in our project to use private ip addressing for the network elements inside of our project and to not expose them to the public internet. CloudSQL DB is our backend service and we would like to keep it this way. In CloudSQL in the Configuration options under "Set connectivity" it's easily possible to select only Private IP addressing. Unfortunately this is not possible while creation of the CloudSQL DB directly from cft.

**Comment by ocsig** [comment]
I believe the following properties can achive your goal:
```
ipConfiguration:
  ipv4Enabled: false
  privateNetwork: YOUR_VPC
```

Please let me know if you managed to make it work, I did not tested myself.

FYI: We are about to merge the dev branch to master, keep an eye out for this, it is a major upgrade. #294 

FYI: To track your feature request: #296

**Comment by ocsig** [comment]
@gdzieleziesz Please check out our latest example:
[cloud_sql_private_network.yaml](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/cft-dm-dev/dm/templates/cloud_sql/examples/cloud_sql_private_network.yaml)
