### ISSUE TITLE
[DM local testing] Docker image and tutorial for local testing 

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#291]
This is a feature request to enable our users to run the bats tests easily with their local codebase.

Key features:
- A container image stored in GCR which can be ran with the path of the bats test as an input parameter
- Dockerfile and cloudbuild.yaml to build this image
- Ability to provide the gcloud credentials from the local system. ( Ideally automatically picking it up, at least in the cloud shell environment.)
- Easy way to provide the required properties for .cloud-foundation-tests.yaml
- Easy way to provide the source code from the local file system. ( The entire templates dir.)
- Readme file which explains how to use the container image locally with docker

This feature is separate from the container used for the CI system.

**Comment by nick4fake** [comment]
@ocsig And a nice entrypoint to simplify running it right from cft repo.
We should also probably allow overriding some values in tests (like "/tmp" prefix for lock files).
