### ISSUE TITLE
Cloud Filestore Template

### ISSUE THREAD

**Issue by farisjarrah** [GoogleCloudPlatform/cloud-foundation-toolkit#301]
### Issue: Template Inquiry

Hello,

I am trying to deploy to cloud filestore via deployment manager/CFT, however, there doesnt seem to be a template for it. Am I missing something?

If one needs to be made for it, I would be down to take a crack at making it, but I just want to ensure that there isn't actually an officially sanctioned method of doing this before I run off and put a ton of work into this.

Any help or insight into this issue would be greatly appreciated. Thanks!

**Comment by morgante** [comment]
Indeed, it looks like there's not.

We'd be happy to look at a PR if you want to contribute one.

**Comment by ocsig** [comment]
Note: gcp-types/file-v1beta1 is supported by DM. Adding it to the backlog.

**Comment by nick4fake** [comment]
Working on this.

**Comment by ocsig** [comment]
FYI #301 is merged to master.
