### ISSUE TITLE
Example Poject template relies on dependencies

### ISSUE THREAD

**Issue by ThomaciousD** [GoogleCloudPlatform/cloud-foundation-toolkit#305]
Hi,

The template [example yaml](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/dm/templates/project/examples/project.yaml) to create a project won't work as a standalone example since it relies on an existing shared vpc host project.
 
Possible fixing:
- either mentioning that a shared vpc named 'test-vpc-host-project' should exist first.
- modify the yaml file to create an autonomous project with its own default network

**Comment by ocsig** [comment]
Cood call. I am extending this Feature request to create 2 additional examples: 

- Standalone Project
- VPC host Project

Additionally extending the example readme/comment to explain the dependencies.

**Comment by nick4fake** [comment]
Working on this.
