### ISSUE TITLE
Instance with private IP example

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#321]
Creation of an example for an instane without a public IP, Optionally with a fix internal IP.
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/565a5513ddafd38c45dc2f6529440ba2f9afd68c/dm/templates/instance/instance.py.schema#L113

**Comment by nick4fake** [comment]
Working on this.
