### ISSUE TITLE
Unable to build docker image from master branch

### ISSUE THREAD

**Issue by red2k18** [GoogleCloudPlatform/cloud-foundation-toolkit#325]
I'm seeing this error while building docker image on the feature branch (with the changes I made) as well as master branch (without any changes).

![image](https://user-images.githubusercontent.com/41486977/64724901-615fc400-d4a1-11e9-8328-5840bbe98701.png)

**Comment by morgante** [comment]
To build the image, you should use `make build-image-developer-tools`.
