### ISSUE TITLE
DM/CLI Cross deployment reference is not even trying to look up the output of the other deployments.

### ISSUE THREAD

**Issue by kopachevsky** [GoogleCloudPlatform/cloud-foundation-toolkit#334]
```
   folders: $(out.act-cft-folders.org-cft-folder.folders)
2019/09/15 00:11:46 Could not find config for deployment = cft-test-workspace-221111.act-cft-folders
```
This error is surfacing within a second, which means, this cross deployment reference is not even trying to look up the output of the other deplyoments.
I am not sure what the error means. Why is it trying to look for a config of the deployment? It should look for the output of the deployment.

**Comment by ocsig** [comment]
More context:
command:
cft apply host-project.yaml

The yaml contains a cross deployment refference. Based on the error message it's clear that itś looking for the right deployment in the right project. What's unclear is why is it looking for a "config" and not for an output.
