### ISSUE TITLE
DM/CLI Hide or list gcloud execution error in case it's expected error

### ISSUE THREAD

**Issue by kopachevsky** [GoogleCloudPlatform/cloud-foundation-toolkit#335]
@ocsig: 
```
I would suggest to either do a list or hide the error. Sang "failed to start cmd: exit status 1" when everything is fine is really confusing.
```

**Comment by ocsig** [comment]
More context:
The CLI output needs to be more clear. Part of this, if there is only expected behvior (like the deployment doesn't exists druing an apply command) there should be no error or warning shown. It's okey to communicate that the deployment doesn't exists and the underlying action is create.
