### ISSUE TITLE
Fix linters to use on modules with `autogen` folder

### ISSUE THREAD

**Issue by paulpalamarchuk** [GoogleCloudPlatform/cloud-foundation-toolkit#338]
* Linter checks don't skip `autogen` folder. (Like in GKE module).
 * Add function `generate` for generation files from `autogen`-folder to the `task_helper_functions.sh`

**Comment by morgante** [comment]
Thanks, please go ahead and pick these tasks up as part of your work to get GKE updated to use the new approach.

One thing to note: while you are developing/testing, you can override and customize the available helper functions: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/concourse/build/developer-tools/build/scripts/task_helper_functions.sh#L408

The workflow I would suggest:
1. Get this all working in GKE
2. Then upstream the required functions into the central image later

**Comment by morgante** [comment]
Priority task: make sure `autogen/` directory is skipped in linters.

Non-priority: upstreaming the generation functionality.
