### ISSUE TITLE
CFT template for CloudRun

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#340]
CloudRun will be soon supported by DM. Having CFT support from day 1 would be awesome.

To create the template we shall use a custom type provider and flip to the native type after go-live. More infor soon.

**Comment by kopachevsky** [comment]
**Issue with Anthos in Cloud Run**

**Comment by bvoss** [comment]
Hi @kopachevsky @ocsig ,
Are there any news here?

I would like to use DM for Cloud Run (fully managed) resources but there isn't still no gcp-type and I can't get a custom type-provider working.

As Cloud Run hast region specific entrypoints as described in https://cloud.google.com/run/docs/reference/rest/#rest_endpoints I get the error

```
{"ResourceType":"<my_project_id>/cloudrun-v1:namespaces.services","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"The
    request has errors","status":"INVALID_ARGUMENT","details":[{"@type":"type.googleapis.com/google.rpc.BadRequest","fieldViolations":[{"field":"region","description":"No
    region provided in host name, in resource name/parent, or in the request."}]}],"statusMessage":"Bad
    Request","requestPath":"https://run.googleapis.com/apis/serving.knative.dev/v1/namespaces/<my_project_id>/services","httpMethod":"POST"}}
```

but the discovery document for https://europe-west1-run.googleapis.com/$discovery/rest?version=v1 also has as baseUrl and rootUrl 'https://run.googleapis.com/'

I tried to download the discovery document and host a patched one by my self to use it for the creation of the custom type-provider but then I get the error

```
code: INTERNAL_ERROR
  message: "Internal error. Please try again or contact Google Support. (Code: '0')"
```
during type-provider creation.

So, is there a way to 
 * use a patch discovery document,
 * get a discovery document with a baseUrl containing the region
 * sending the region via request parameter/header and input mapping
 * or do you know when the gcp-typ will be available?

Thx

**Comment by ocsig** [comment]
Hi Björn,

Thank you for your deep work, I really appriciate the effort your put in to this type.

Unfortunately your discovery is correcty, let me try to answer your questions:
- Hosting a discovery document in a public endpoint, like a Cloud Storage Bucket works well during custom type creation.
- The CloudRun team is currently working on the regional discovery document with the correnct baseUrl.
- We had a deep look but after discussing with DM engineers, this is not possible, because DM does not support input mapping to the baseURL. What is possible is to create a template which gets a region parameter and based on this value its choosing the right ( regional) CloudRun type. This needs point 1-2 working.
- The GCP type will be available shortly after the CloudRun team patched the disco-docs.

I will ask the DM team about the internal error, because if I remember right @kopachevsky managed to make this work. Let me update you here mid-next week.

**Comment by bvoss** [comment]
Hi Adam

Thank you for your answer and support. I was a bit busy the last days. So if I can support you with any additional information to help you for the DM error on hosting a patched discovery doc, just let me know.

**Comment by bvoss** [comment]
Hi Adam @ocsig 

Any news here?

Because I played a bit with hosting descriptor/swagger2 files. And what confused me was, that I get the 
```
code: INTERNAL_ERROR
  message: "Internal error. Please try again or contact Google Support. (Code: '0')"
```
on type provider creation also on other Google APIs with the unchanged discovery docs hosted on my public bucket.

**Comment by ocsig** [comment]
No update yet. Periodically bringing this issue up for the team.
