### ISSUE TITLE
Exclude picture-files from lint tests

### ISSUE THREAD

**Issue by paulpalamarchuk** [GoogleCloudPlatform/cloud-foundation-toolkit#364]
No need to run tests on picture files, like `*.png`. 
Example from [VPC Service Controls module](https://github.com/terraform-google-modules/terraform-google-vpc-service-controls)
```
Checking for missing newline at end of file
Error: No newline at end of file ./examples/automatic_folder/diagram.png
```

**Comment by morgante** [comment]
This should be a very straightforward change to the find_files def.
