### ISSUE TITLE
Getting rid of glue code which pipes tf outputs from setup to kitchen_do

### ISSUE THREAD

**Issue by cray0000** [GoogleCloudPlatform/cloud-foundation-toolkit#386]
I have a proposition to remove the requirement for explicitly defining the `test/setup/make_source.sh` script. Instead I think there is a pretty generic way to hide this functionality inside the `kitchen_do` command itself.

Here is what I think `kitchen_do` can perform right before the other stuff it does now:

1. run `terraform output -json` from the `test/setup` directory.
2. parse the JSON output, and dynamically do bash `export TF_VAR_{name}={value}` for each output value.
3. Handle the magic var `SERVICE_ACCOUNT_JSON` in a special way. I looked through the source code of several repos and looks like everywhere the naming and the command to obtain it is consistent. If the terraform variable `sa_key` exists, we'll perform the magic routine to setup the `SERVICE_ACCOUNT_JSON` out of it.
4. And we KEEP the old functionality -- if the `make_source.sh` exists, the setup script will execute it like it does now and the `kitchen_do` will just use it to override the variables defined implicitly. This way if there are some other magic variables like `SERVICE_ACCOUNT_JSON`, devs can just explicitly set them up.

I should be able to make prototype of this and integrate into several modules to test it pretty quickly. Since the dev tools live in a docker image, I can use python to parse json, so it should be pretty simple and straightforward to implement.

Would love to hear what you think about it.

**Comment by morgante** [comment]
This sounds like a great idea.

Two caveats:
1. If test/setup has *not* been provisioned, we should proceed gracefully (ie. setting all values via `make_source.sh` or env variables should still be supported)
2. Consider options for having `terraform output -json` provided from a prebuilt file (we might want to pre-provision projects in the future).
