### ISSUE TITLE
Add infrastructure for cleaning up old test projects

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#400]
We need to add infrastructure for cleaning up old test projects so they don't continue to cost us money. The work involved should be:

1. Updating [this module](https://github.com/terraform-google-modules/terraform-google-scheduled-function/tree/master/modules/project_cleanup) with additional inputs:
    - A provided folder ID to delete all projects under (see #306 for reference) **unless**
    - A provided exclude_label value is provided (ex. `exclude_labels: {cft-testing: persistent}`)
2. Adding a config in `infra/terraform/test-org/test-cleanup/` which sources the project cleanup module and instantiates it on our org. Work began on this [here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/399), please pick up from that PR.

**Comment by paulpalamarchuk** [comment]
@morgante Additional input `exclude_labels` should be string or list of strings? If it's list, then it have to be JSON format or YAML, or any other format?

**Comment by morgante** [comment]
`exclude_labels` should be a map of key/value pairs.

**Comment by aaron-lane** [comment]
@paulpalamarchuk can you clarify what you mean by 

> folder ID affect old inputs

**Comment by paulpalamarchuk** [comment]
@aaron-lane If `folder_id` is not set, does the func have to delete all the projects(which have defined labels) within the org? I think it's unsafe.

**Comment by morgante** [comment]
> @aaron-lane If folder_id is not set, does the func have to delete all the projects(which have defined labels) within the org? I think it's unsafe.

I think we can make folder_id required.
