### ISSUE TITLE
Automate Cloud Build triggers using Terraform

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#405]
Now that Terraform has [support for Cloud Build](https://www.terraform.io/docs/providers/google/r/cloudbuild_trigger.html), we should automate the triggers from the [CFT CI docs](https://docs.google.com/document/d/1eiHpZlhEDMDG8gi4LHyv2aZs1TJmeFlF8sqCE57_j4A/edit). This should be done in a DRY way using `for_each` so we can easily add standard triggers for new modules with minimal effort.

**Comment by paulpalamarchuk** [comment]
Started working on that feature
