### ISSUE TITLE
CFT CLI supports 'validate' command and --validate flag

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#420]
The CFT CLI should support new syntaxes:
```
cft validate DEPLOYMENT_NAME --policy-path=${POLICY_PATH}
cft validate DEPLOYMENT_NAME --policy-path=${POLICY_PATH} --project=MyPROJECT
cft apply deployment.yaml --preview --validate --policy-path=${POLICY_PATH}
```
Note: --project is optional, gcloud config project should be used by default.
`cft validate` is querying an existing (in preview) deployment.
`--validate` is only allowed together with the `--preview`, this calls cft validate after the preview is created.

**Comment by nick4fake** [comment]
Few notes:
- "create" should be supported too
- It shouldn't matter if deployment is in the preview mode, technically this limitation doesn't change anything
- We can do validation for multiple templates/deployments too
