### ISSUE TITLE
DM validator supports gcp-types/compute-v1:firewalls

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#421]
Dependent on #420 

`cft validate` command parses thrugh the DM resources in the preview manifest. Ignores every type except the supported ones.
At this stage, the only supported type is `gcp-types/compute-v1:firewalls`.
Transforms this type into a valid Cloud Asset Inventory object.

Unit tests for the pharsing and transformation.

**Comment by nick4fake** [comment]
https://github.com/forseti-security/policy-library/issues/112
