### ISSUE TITLE
Forseti template does not support CAI

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/cloud-foundation-toolkit#43]
Forseti now supports cloud asset inventory. The DM template does not have support for setting this however.

The terraform module (https://github.com/forseti-security/terraform-google-forseti) supports cai through the following vars:
- enable_cai_bucket
- bucket_cai_lifecycle_age
- bucket_cai_location
- cai_api_timeout

**Comment by ocsig** [comment]
Wont fix
