### ISSUE TITLE
DM Validatos support multiple project types

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#437]
All GA types should be supported:

```
gcp-types/cloudresourcemanager-v1:projects
cloudresourcemanager.v1.project
```

**Comment by nick4fake** [comment]
For billing validation: https://github.com/forseti-security/policy-library/issues/223

**Comment by morgante** [comment]
@nick4fake If you just need a policy to test with, you can use `always_violates` or the banned resource type policy.
