### ISSUE TITLE
Add an Identity-Aware Proxy (IAP) example

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/cloud-foundation-toolkit#444]
I would like to configure [the steps at https://cloud.google.com/iap/docs/enabling-kubernetes-howto](https://cloud.google.com/iap/docs/enabling-kubernetes-howto) using deployment manager, at least everything until the section `Configuring BackendConfig` and below.

Having everything needed for Identity-Aware Proxy (IAP) deployed through deployment manager would increase repeatabilty and reduce the risk for error.

**Comment by ocsig** [comment]
Thank you for your contribution, this is a great request!
The required API for IAP consent screen and Client OAuth is under development, currently internally accessible only. We will keep a close eye on the API release and implement the DM type and the CFT example after it's release.

The 3rd step looks to me an IAM binding, which is currently supported as an action in DM, however the product team works on the roll-out of the `gcp-types/*:virtual.*.IAMMemberBinding`

**Comment by ocsig** [comment]
The API for the consent screen and Client Oauth is publicly awailable and it looks like it is usable as a GCP type:
https://cloud.google.com/iap/docs/programmatic-oauth-clients

I will do further testing.
