### ISSUE TITLE
DM Validator Unit tests

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#456]
Unit testing the already implemented GCP types and basic validtion.

**Comment by nick4fake** [comment]
@ocsig https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/434
Do you think that is the right approach?

**Comment by morgante** [comment]
@nick4fake We should not use bats for integration tests, but instead use normal Go testing methods. Please follow the example of how this is done in Terraform Validator (and put tests in a separate PR, not the same PR): https://github.com/GoogleCloudPlatform/terraform-validator/tree/master/test

**Comment by nick4fake** [comment]
@morgante I was following existing approach.
Plus this issue is only related to unit tests that are fully written on go, I've added function tests as a bonus.

**Comment by morgante** [comment]
@nick4fake Please put them in a separate PR then. I don't want bats tests for Go code going forward.
