### ISSUE TITLE
PostgreSQL 11 Support for cloud_sql.py

### ISSUE THREAD

**Issue by trevorjwilliams** [GoogleCloudPlatform/cloud-foundation-toolkit#457]
Right now in cloud_sql.py.schema, the `databaseVersion` enum is defined as:

```
    enum:
      - MYSQL_5_5 # Deprecated
      - MYSQL_5_6
      - MYSQL_5_7
      - POSTGRES_9_6
```

Given that Postgres 11 went GA on 2019.09.27 and became the default Postgres version (https://cloud.google.com/sql/docs/postgres/release-notes), it would be helpful if `POSTGRES_11` were added to this.

Note that before this constraint was added to the template, I was able to use it to successfully initialize a Postgres 11 database, though I did not thoroughly test it to see if there were any issues with it.

**Comment by ocsig** [comment]
Thank you for contributing and highlighting this! 

We are currently revisiting the supported `databaseVersion` field to support MSSQL as well. I will make sure it is up to date. ( What's important is that the [discovery doc](https://sqladmin.googleapis.com/$discovery/rest?version=v1beta4) supports your version.) 
As a 0 effort fix, feel free to extend the schema file on your end, it is only there as a safeguard for you.
#445 

```yaml
          "enum": [
            "OBSOLETE_MYSQL_5_0",
            "MYSQL_5_1",
            "MYSQL_5_5",
            "MARIADB_10_0",
            "MYSQL_5_6",
            "MYSQL_5_7",
            "OBSOLETE_POSTGRES_9_5",
            "SQLSERVER_ENTERPRISE_2016",
            "POSTGRES_9_6",
            "POSTGRES_11",
            "SQLSERVER_2017_STANDARD",
            "SQLSERVER_2017_ENTERPRISE",
            "SQLSERVER_2017_EXPRESS",
            "SQLSERVER_2017_WEB"
          ],
```

**Comment by trevorjwilliams** [comment]
Yup, looks like that takes care of my request. Thanks!
