### ISSUE TITLE
dns templates do not properly implement deletion

### ISSUE THREAD

**Issue by frots** [GoogleCloudPlatform/cloud-foundation-toolkit#466]
Unable to remove records or DM resource. Even when feeding an empty set of resources dm tries to POST and complains about missing entity.change parameter. When looking at the API reference it appears DM uses wrong method and should use DELETE:
```- code: RESOURCE_ERROR
  location: /deployments/myproject/resources/myrecord-resource
  message: "{\"ResourceType\":\"gcp-types/dns-v1:resourceRecordSets\",\"ResourceErrorCode\"\
    :\"400\",\"ResourceErrorMessage\":{\"code\":400,\"errors\":[{\"domain\":\"global\"\
    ,\"message\":\"The 'entity.change' parameter is required but was missing.\",\"\
    reason\":\"required\"}],\"message\":\"The 'entity.change' parameter is required\
    \ but was missing.\",\"statusMessage\":\"Bad Request\",\"requestPath\":\"https://dns.googleapis.com/dns/v1/projects/myproject/managedZones/myrecord-resource/changes\"\
    ,\"httpMethod\":\"POST\"}}"```

**Comment by ocsig** [comment]
This looks like an issue with `gcp-types/dns-v1:resourceRecordSets`.
Please follow [https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/509](https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/509) for tracking. I escalate this with the DM team.
