### ISSUE TITLE
TargetProxy sslCertificates - KeyError

### ISSUE THREAD

**Issue by maciej-ziebicki** [GoogleCloudPlatform/cloud-foundation-toolkit#484]
During elastic_load_balancer implementation it was discovered that the template does not support sslCertificates array (according to elastic_load_balancer.schema). Therefore separate implementation of all components has to be done (healthcheck, backend_service, url_map, target_proxy and forwarding_rule). There is a KeyError issue obtained during sslCertificates configuration of target_proxy. The template itself allows to provide sslCertificates in a format:

      ssl:
        sslCertificates:
            - <CERT1_URL>
            - <CERT2_URL>
            - <CERT3_URL>

but the error is obtained:

Manifest expansion encountered the following errors: Exception in target_proxy.py
Traceback (most recent call last):
    return constructor\[m\](evaluation_context)
  File "<string>", line 160, in generate_config
  File "<string>", line 138, in get_https_proxy
  File "<string>", line 115, in get_secure_proxy
KeyError: 'certificate'

Please check if it's a bug. If it's not a bug please advise how to implement sslCertificates correctly.

**Comment by maciej-ziebicki** [comment]
I also found out the I cannot refer to url map resource in target proxy in target tag in $(out.\<project\>.\<deployment\>.\<resource\>.\<output\>) format. I can provide a direct url though. unfortunately it's not satisfactory since this dependency is required to make the whole deployment work.

**Comment by ocsig** [comment]
Thank you for highlighting this!

The targetProcy template supports the sslCertificates url list:
[target_proxy.py.schema#L92](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/e8e990cc9b487d1a7d578520c21e57eace60b222/dm/templates/target_proxy/target_proxy.py.schema#L92)

However the [External LoadBalancer schema ](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/e8e990cc9b487d1a7d578520c21e57eace60b222/dm/templates/external_load_balancer/external_load_balancer.py.schema#L455) file does not allow this, which is clearly a bug, we will fix this shortly.

Let me look deeper into your other error.
