### ISSUE TITLE
Extend (new) CFT CLI readme with DM related info

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#499]
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/cli

Missing commands such as apply, (create), delete.

Missing info about flags such as preview and validate.

It is okey to copy part from the user guide here. This does not need to be full but should refer for further info if needed.

**Comment by morgante** [comment]
We could generate the docs here: https://github.com/spf13/cobra/blob/master/doc/md_docs.md
