### ISSUE TITLE
Bug in firewall template 

### ISSUE THREAD

**Issue by frots** [GoogleCloudPlatform/cloud-foundation-toolkit#502]
When  `sha1(rule['name']).hexdigest()[:10]` generates a hash that matches an exponential number notation, DM errors with something like:
```googlecloudsdk.api_lib.deployment_manager.exceptions.OperationError: Error in Operation [operation-000000-00000-000-000]: errors:
- code: INVALID_CONFIG
  message: "Invalid config files: Template fetching failed: Failed to parse template\
    \ name 7.7727716E8 since it's not a String.."
```

In this case the hash function resulted in string '77727716e8' and apparently somewhere it is cast to non string type.

**Comment by ocsig** [comment]
Thank you for this, we will investigate this issue. If it is a bug, it's in every template.

**Comment by frots** [comment]
I think so , it might be related to https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/417

**Comment by frots** [comment]
Hi @ocsig, was a fix for this already merged?
