### ISSUE TITLE
DM Cloud Router doesn't permit Cloud NAT creation

### ISSUE THREAD

**Issue by Abdennebi** [GoogleCloudPlatform/cloud-foundation-toolkit#508]
Hi,

This because of the presence of  the required field ``asn`` which is not required when you create a cloud NAT (when present an error is raised saying 

> Creating a router with multiple features is currently unsupported.

As workaround I commented out the ``bgp`` field into  the ``cloud_router.py`` template.

Next I faced a problem with the [schema](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/dm/templates/cloud_router/cloud_router.py.schema) as it moved mistakenly some fields that belong to ``nats``to ``subnetworks``.

The fields that are not in the right place are :
```
- natIps
- natIpAllocateOption
- minPortsPerVm
- udpIdleTimeoutSec
- icmpIdleTimeoutSec
- tcpEstablishedIdleTimeoutSec
- tcpTransitoryIdleTimeoutSec
- logConfig
```

**Comment by ocsig** [comment]
Thank you for highlighting this, we add it to our backog as P1.

We also need to add a CloudNAT example and test.
