### ISSUE TITLE
License header check is failing on valid files

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#513]
Perfectly valid license headers, like [this file](https://github.com/terraform-google-modules/terraform-google-log-export/blob/master/test/integration/bigquery/folder/controls/gcloud.rb) are failing the header check on the latest devtools image.

**Comment by omazin** [comment]
Is this issue still relevant? Ran the headers check using the latest devtools image on the [log-export](https://github.com/terraform-google-modules/terraform-google-log-export ) module without any errors.
