### ISSUE TITLE
Folder template returns a map instead of an array

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#554]
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/6f99a46c25d2343f440306385c9f802b3304207a/dm/templates/folder/folder.py.schema#L111

The schema states incorrectly the returned output. `folders` is a map, not an array.

**Comment by komasoftware** [comment]
vice versa, the schema incorrectly states it is an array, but it is a map
