### ISSUE TITLE
security command center automation

### ISSUE THREAD

**Issue by SprintCT** [GoogleCloudPlatform/cloud-foundation-toolkit#576]
Hi Team,

Is there any automation code (jinja/python) to add the asset in security command center in GCP deployment manager.
I could find the API of security command center API, however there is no gcp-types or types for security command center. Can anyone help me on this.

**Comment by katze120** [comment]
Assets inside Google Cloud Security Command Center are automatically discovered and do not need to be explicitly added.
Documentation regarding asset freshness: https://cloud.google.com/security-command-center/docs/how-to-assets-display#viewing_assets
