### ISSUE TITLE
[Feature Request] Support delete-policy in the cli

### ISSUE THREAD

**Issue by rick-pri** [GoogleCloudPlatform/cloud-foundation-toolkit#578]
In deployment manager you can pass the `--delete-policy` flag set to `ABANDON` to override the default `DELETE` policy so as not to delete resources when they are removed from a deployment.  

This allows you to get around issues where DM doesn't have the feature set that's available through the UI so that you can abandon the resources, make the change and then reacquire them on a subsequent run.

**Comment by ocsig** [comment]
Are you using the pyhton CLI (https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/src) or the not yet released GO CLI? (https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/cli)

**Comment by rick-pri** [comment]
I'm using the python cli, as per the readme instructions **[here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/dm/docs/userguide.md#toolkit-installation-and-configuration)**.  I didn't know about the go cli.
