### ISSUE TITLE
Scorecard - behaviour changes with new config-validator

### ISSUE THREAD

**Issue by katze120** [GoogleCloudPlatform/cloud-foundation-toolkit#584]
Keeping a list of scorecard behaviour changes with new config-validator here, and investigation notes on whether each of them is a feature or a bug and how should each be handled.

- [Resolved] violation metadata now moved under metadata.details
  - handled in https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/575 https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/575/commits/37cade60fc28db6989ec22d4963cf570a552aae3

- [No action required - keep in mind for constraint development] all underscore in constraint names are replaced by dash
  - feature for compatibility with gatekeeper
  - update [policy-library samples](https://github.com/forseti-security/policy-library/tree/master/samples) to avoid user confusion

- [No action required - keep in mind for constraint development] all k8s resources are transformed to admission controller format
  - feature for compatibility with gatekeeper
  - k8s resources will no longer work with existing config validator constraints, if any 
  - no existing policy-library samples in OSS repo with k8s resources

- [Resolved] duplicate violations, with a few situations:
  - upstream issue: https://github.com/forseti-security/config-validator/issues/116
  - attempt to fix in scorecard: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/586
  - Rego optimization in some constraint templates needed
    - e.g. review [GCPStorageBucketWorldReadableConstraintV1](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_storage_bucket_world_readable_v1.yaml)
  - Some duplicates may exist in raw CAI data
    - e.g. review iam-policy raw CAI data and [GCPIAMAllowedBindingsConstraintV1](https://github.com/forseti-security/policy-library/blob/master/policies/templates/gcp_iam_allowed_bindings_v1.yaml). 
  - Note: Forseti ensures unique findings are written to CSCC by keeping a hash of violation data.

- data in [ConstraintConfig](https://github.com/forseti-security/config-validator/blob/master/pkg/gcv/cf/parsing.go#L32) is missing
  - constraint name missing when output format is txt, due to scorecard [GetName](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/cli/scorecard/score.go#L87) function returning empty string
  - constraint categories all become 'Other'. 
  - upstream issue: https://github.com/forseti-security/config-validator/issues/120
  - attempt to fix constraint name in scorecard: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/586 (this PR fixes constraint names but not constraint category)
  - permanent fix including new changes in upstream config validator: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/613

**Comment by morgante** [comment]
> In general, should scorecard remove duplicate violations?
I'd like us to log the duplicates so we know there's an issue, but to keep behavior identical I think we can remove duplicates.
