### ISSUE TITLE
CloudSQL users unmanageable

### ISSUE THREAD

**Issue by davidebelloni** [GoogleCloudPlatform/cloud-foundation-toolkit#597]
Hi,
using CloudSQL template for CloudSQL MySQL and configuring some users return the following error since the second time configuration are deployed:

```
- code: MISSING_METHOD_IN_COLLECTION
  message: Method 'get' does not exist for collection 'users' in descriptor url 'https://www.googleapis.com/discovery/v1/apis/sqladmin/v1beta4/rest'
```
So, the first time instance and users are created, after the deployment is no more applicable (also without modifying users)

I've found a similar issue: https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/142

This make the template unusable

Thanks

**Comment by maodijim** [comment]
For people who are facing the same issue solution is: 
```
# Failed one
- name: {{ deployment }}-dbUser
  type: gcp-types/sqladmin-v1beta4:users

# Correct one
- name: {{ deployment }}-dbUser
  type: gcp-types/sqladmin-v1beta4:sql.users.insert
```

After examine the descriptor json https://sqladmin.googleapis.com/$discovery/rest?version=v1beta4
There are four methods available: `sql.users.list, sql.users.insert, sql.users.delete, sql.users.update`
