### ISSUE TITLE
SERVICE_ACCOUNT_JSON env var typo

### ISSUE THREAD

**Issue by linde** [GoogleCloudPlatform/cloud-foundation-toolkit#639]
i think the script in the docker image expects the value of the credential, not a path to it to be passed in as an environment variable. 

so in 4.2 Setup Terraform Credential on ([step 4](https://codelabs.developers.google.com/codelabs/cft-onboarding/#3)) the command should be the following or something similar, i think:
```
export SERVICE_ACCOUNT_JSON=$(< cft.json)
```
and the text needs to reflect that it is the value, not the path.

**Comment by morgante** [comment]
Thanks, updated!
