### ISSUE TITLE
Support Cloud Scheduler in Deployment Manager

### ISSUE THREAD

**Issue by bbzg** [GoogleCloudPlatform/cloud-foundation-toolkit#662]
# Cloud Scheduler
I would like to be able to configure Cloud Scheduler using Deployment Manager.

There is already an issue here https://github.com/GoogleCloudPlatform/deploymentmanager-samples/issues/369 and here https://issuetracker.google.com/issues/123013878 but they have not received any good responses for over a year.

# Aside

I have been using Deployment Manager for over two and a half years. I really don't want to complain, and have been trying to stay positive in my comments, but I have to admit that I am losing hope for Deployment Manager. I have been thinking of switching over to something else, e.g. Terraform but it's just such a monumental task at this point.

There are so many services and sub-features missing at this point (or at least are so undocumented and convoluted that I have not found how to do them), and have been missing for such a long time:

* Serverless VPC Connector
* secrets add-iam-policy-binding
* iam service-accounts add-iam-policy-binding
* Secret Manager Create
* Equivalent of gsutil iam ch for a service account on a bucket

Furthermore it is semi-annoying that some types are not "Infrastructure as Code" but just really "We wrapped this create request as a type" and when the resource is removed I have to figure out how to remove all dependencies.

# Sorry

Sorry for being so negative, but I really like the scriptability and expressiveness of Deployment Manager, and I would like it to be more complete. I really don't like the thought of having to run a bunch of shell scripts to bring up or change my services.

**Comment by bbzg** [comment]
Definition of Done for any GCP Beta product should really include Deployment Manager. It's hygiene at this point. You wouldn't deploy a service without writing tests?

**Comment by aahventures** [comment]
I have the same feeling. It just feels so incomplete and unsupported. It's a great tool otherwise. I probably would have switched to Terraform if it wasn't for the fact that I need to manage my own state.

**Comment by red8888** [comment]
how does terraform, a 3rd party tool, have better support for this?

I want to deploy a cloud function along with a cloud scheduler task. I could do that in terraform but its not really designed for deploying software. I want to have a cloud function and scheduler task neatly described in one deployment manager template I can deploy as a single stack and manage as a single object

I get the feeling deployment manager isn't fun to work on at google or something. Google contributes directly to terraform so I suspect thats more fun for their engineers than writing code for some proprietary tool :)

**Comment by bbzg** [comment]
I took on the task of rewriting everything in Terraform (and I am complete), and since no one has answered this for a long while I am closing the issue.

**Comment by dinigo** [comment]
Close to two years ago I made the request to GCP support to implement this feature. It looks like they have finally implemented it. As @red8888 did we too consider Terraform as the go-to solution for maintaining and reproducing deployment architectures since DM is not a reliable product and completely lacks support.

It's a shame because I like the static file approach. Similar to what Helm does with kubernetes
