### ISSUE TITLE
CFT Scorecard: json parser seems parse inventory line by line

### ISSUE THREAD

**Issue by xingao267** [GoogleCloudPlatform/cloud-foundation-toolkit#714]
It looks like the Scorecard parse CAI json data line by line. If I reformat the json file to be more human readable, then Scorecard would fail and gives json paring error, e.g.

```json
Error: Fetching inventory from local directory: converting asset { to proto: marshaling to interface: unexpected end of JSON input
```

**Comment by morgante** [comment]
Yes, it parses line-by-line. This is because the CAI output is *not* a JSON array but rather a dump of assets (one-per-line) encoded as json.

I'm inclined to close this as WAI.

**Comment by xingao267** [comment]
Ok. Thanks!
