### ISSUE TITLE
simple-project and owned-project fields should be strings

### ISSUE THREAD

**Issue by trodge** [GoogleCloudPlatform/cloud-foundation-toolkit#718]
In the simple-project and owned-project helm solutions, the orgID and folderID fields need to be enclosed in quotes to be interpreted as strings rather than integers. Helm converts them to integers currently which does not work with KCC.

**Comment by BrianPi** [comment]
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/721
