### ISSUE TITLE
Provide a fully working example of connecting a GKE pod to the private IP of a CloudSQL instance

### ISSUE THREAD

**Issue by paulczar** [GoogleCloudPlatform/cloud-foundation-toolkit#722]
I recently went through a lot of pain to figure out how to do this, it feels like this should be a fairly common pattern and it would be great to have better documentation and examples on how to do it.

Here's the bug report on google config connector that describes the trouble I had and the eventual solution as a guide.

https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/201

**Comment by toumorokoshi** [comment]
There is already a working example, referenced in the k8s-config-connector issue: https://github.com/paulczar/gcc-cloudsql
