### ISSUE TITLE
Log sink template could be more flexible

### ISSUE THREAD

**Issue by umairidris** [GoogleCloudPlatform/cloud-foundation-toolkit#77]
Our current deployment looks something like this:
- Log sink deployed on project-foo
- Get log sink writer and set in dataset
- Deploy dataset in project-bar

Two deployments in two projects.

The current template has a few problems with this:
- it doesn't allow cross project sinks
- due to the writer service account being in the form seviceAccount:foo@google.com the bigquery access field cannot be set.

It would be great if cross project sinks + some workaround for the dataset could be made. Perhaps it can do some project id matching inside the template and the same template can be deployed in both projects and it will be smart enough to know which resource to deploy in which project?

**Comment by kopachevsky** [comment]
@umairidris did I understand your request correctly: first and simplest case is when logsink destination located in other project? and it's not nessesary bigquery one?

saying true, didn't understand this statement:

> due to the writer service account being in the form seviceAccount:foo@google.com the bigquery access field cannot be set.

**Comment by morgante** [comment]
@kopachevsky I'd say let's start by supporting cross-project log sinks (for all destinations).

**Comment by umairidris** [comment]
Hi Andriy,

We use terraform now and are able to set this in the deployment:
```
resource "google_biquery_dataset" "logs_dataset" {
  ...
  user_by_email = replace(google_logging_project_sink.sink.writer_identity, "serviceAccount:", "")
}
```

I don't believe this is possible in deployment manager (at least when I opened this bug). If you try to set user_by_email = serviceAccount:foo it will fail. So this made it impossible to deploy the sink + its dataset in the same deployment.

You can see the comment in the template: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/dm/templates/logsink/logsink.py#L173

We typically create per-project sinks and have them export to datasets in a central project. It makes it easy for a team to have one place to see the audit logs of all their projects.
