### ISSUE TITLE
Need a more recent version of inspec

### ISSUE THREAD

**Issue by parabolic** [GoogleCloudPlatform/cloud-foundation-toolkit#774]
Hi, 
I've seem to run into issue with running inspec  integration tests for a gcp resource , namely `google_compute_router`. The error I am getting is 
```sh
inspec-gcp: Verifying
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [Train::Transports::Gcp::Connection does not implement #run_command_via_connection()] on simple-example-loc
al
>>>>>> ----------------------
```
and after manually upgrading inspec and kitchen-terraform from within the docker, I am able to conduct the tests successfully.
Is there an easy way to bump the inspec version to the latest version  preferably https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/data/Gemfile.lock#L109 ? I am not sure at which point the `run_command_via_connection` method was added.

There's more information on the following PR https://github.com/terraform-google-modules/terraform-google-cloud-router/pull/11

Thanks!

**Comment by morgante** [comment]
Hi! if you can open a PR on this repo with the desired changes to the Docker build we can definitely review/release.

**Comment by parabolic** [comment]
Solve with https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/776
