### ISSUE TITLE
Broken Link for Forseti

### ISSUE THREAD

**Issue by ericyz** [GoogleCloudPlatform/cloud-foundation-toolkit#790]
The link is broken [Cloud Foundation Toolkit Page]( in https://cloud.google.com/deployment-manager/docs/reference/cloud-foundation-toolkit)

Broken Link:
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates/forseti

Possible Action:
- Add readme in templates for forseti
- Remove the link for Froseti in [Cloud Foundation Toolkit Page]( in https://cloud.google.com/deployment-manager/docs/reference/cloud-foundation-toolkit)

**Comment by morgante** [comment]
cl/330960997
