### ISSUE TITLE
Addons_config must be specified.

### ISSUE THREAD

**Issue by DracoBlue** [GoogleCloudPlatform/cloud-foundation-toolkit#799]
Hello,

starting today, we cannot upgrade our clusters anymore by using google deployment manager.

It says:

```
 Waiting for update [operation-1601375718872-5b07156e016f9-eff9e8bf-a4b95a14]...
 .....................failed.
 ERROR: (gcloud.deployment-manager.deployments.update) Error in Operation [operation-1601375718872-5b07156e016f9-eff9e8bf-a4b95a14]: errors:
 - code: RESOURCE_ERROR
   location: /deployments/TOP-SECRET-cloud-test-deployment/resources/TOP-SECRET-cloud-test-cluster
   message: '{"ResourceType":"gcp-types/container-v1beta1:projects.locations.clusters","ResourceErrorCode":"400","ResourceErrorMessage":{"code":400,"message":"Addons_config
     must be specified.","status":"INVALID_ARGUMENT","statusMessage":"Bad Request","requestPath":"https://container.googleapis.com/v1beta1/projects/TOP-SECRET-cloud-test/locations/europe-west3/clusters/TOP-SECRET-cloud-test-cluster:setAddons","httpMethod":"POST"}}'
```

We checked if addonsConfig is set - it is. But I am confused why it says it's missing "Addons_config" :(

**Comment by frots** [comment]
I'm noticing the same problem since recently.

**Comment by shalomcbouncex** [comment]
Same here, did any of you made progress with this issue?

**Comment by shalomcbouncex** [comment]
We have experienced the exact same issue, it disappeared for a while and now returned all of the sudden. anyone from google is looking into it? the ticket is open from last year?

**Comment by cvermilion** [comment]
I've hit the same issue now, and no luck figuring out what's going on. The only clue I've found is [this cryptic comment](https://cloud.google.com/deployment-manager/docs/best-practices#managing_resources) in the best practices doc:

> After you have created a resource as part of a deployment, use Deployment Manager if you need to modify the resource. If you modify a resource without using Deployment Manager, such as with the Cloud Console or gcloud you might see errors if you try to modify the resource in your original deployment.

**Comment by antoinedeschenes** [comment]
Also just hit the issue trying to update a deployment. Even when trying to modify addonsConfig we get the same message.

**Comment by cvermilion** [comment]
lol. lmao.
