### ISSUE TITLE
Can't remove Node Pool using deployment-manager

### ISSUE THREAD

**Issue by risayew** [GoogleCloudPlatform/cloud-foundation-toolkit#807]
Hi Everybody.
How to delete node pool with deployments-manager ? I did try the following:

delete the pool from .yml file, the gcloud deployment-manager deployments update this did not work and threw an error InputMapping for field [name] for method [delete] could not be set from input, mapping was: [$.concat($.resource.properties.parent, "/clusters/", $.ifNull($.resource.properties.name, $.resource.name), "/nodePools/", $.getElement($.resource.previous.cluster.nodePools, $.matches[0], "name"))
deleted finally the old node pool from WEB console manually and afterwards from .yml file, but now cant’ update anyting with deployment-manager at all

**Comment by risayew** [comment]
https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/issues/441

**Comment by shalomcbouncex** [comment]
Any updates, I got the same issue as well.
