### ISSUE TITLE
Remove all usage of actions

### ISSUE THREAD

**Issue by ocsig** [GoogleCloudPlatform/cloud-foundation-toolkit#837]
The CFT maintainer team decided to remove all usage of alpha features such as actions to create a more stable codebase and reduce constant maintenance.

**Comment by ocsig** [comment]
Depends on:

- [ ] #838
- [ ] #839
- [ ] #840
- [ ] #841
- [ ] #842
- [ ] #843
- [ ] #844
- [ ] #845
- [ ] #846
- [ ] #847
- [ ] #848
- [ ] #849

**Comment by frots** [comment]
Does this mean development for the missing backend features is going to be sped-up?

**Comment by morgante** [comment]
Closing this since #850 was merged.
