### ISSUE TITLE
Provide kpt template for other gcp resources 

### ISSUE THREAD

**Issue by yashsaini77** [GoogleCloudPlatform/cloud-foundation-toolkit#851]
Please provide the KPT templates for other GCP resources as well we need them urgently please help. 
- Compute Engine (Instance)
- Custom VPC(Network, Subnetwork)
- GKE Cluster (having custom node-pool)

**Comment by morgante** [comment]
Hi, have you seen the Config Connector [samples repo](https://github.com/GoogleCloudPlatform/k8s-config-connector/)? It has a lot more examples which might be helpful.

**Comment by yashsaini77** [comment]
Hi @morgante I am not asking for these samples which you are mentioning I am asking for KPT templates where KPT file is also there with sample YAML files for resources so that it can work with KPT way as [KPT](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/config-connector/solutions/projects/kpt)

**Comment by yashsaini77** [comment]
Hi @morgante, Can we have it as soon as possible as it is urgent?

**Comment by morgante** [comment]
@yashsaini77 This is still in the backlog, but you should be able to build a package yourself based on the KCC samples.

**Comment by yashsaini77** [comment]
@morgante , I am not sure if I can create a correct KPT file for the resources I mentioned above, can you please help to create KPT file for these resources.
