### ISSUE TITLE
License header checker fails for Dockerfile and yaml

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#870]
It seems to complain about perfectly valid Dockerfile headers.

Ex. https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/808

**Comment by Shabirmean** [comment]
I think this can be closed now that https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/pull/954 is meged

**Comment by morgante** [comment]
Indeed, thanks @Shabirmean!
