### ISSUE TITLE
need to upgrade kitchen-terraform version for cft/developer-tools:0.15

### ISSUE THREAD

**Issue by chaopeng** [GoogleCloudPlatform/cloud-foundation-toolkit#916]
Got error: Step #1 - "create": $$$$$$ Verifying the Terraform client version is in the supported interval of >= 0.11.4, < 0.14.0...

It is because we [still use kitchen-terraform 5.5.0](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/infra/build/developer-tools/build/data/Gemfile), but it require upgrade to support terraform 0.15 

- https://github.com/newcontext-oss/kitchen-terraform/tree/v5.7.2
- https://github.com/newcontext-oss/kitchen-terraform/tree/v5.5.0

**Comment by bharathkkb** [comment]
@chaopeng I believe supporting 0.15 in  kitchen-terraform is still WIP https://github.com/newcontext-oss/kitchen-terraform/pull/452

**Comment by chaopeng** [comment]
Sorry I only read this doc https://github.com/newcontext-oss/kitchen-terraform/tree/v5.7.2#terraform

**Comment by morgante** [comment]
@chaopeng For now I disabling `verify_version` in the test config (https://github.com/terraform-google-modules/terraform-google-folders/blob/b335283d51bc03977f8f923b198115866aef52d6/kitchen.yml#L18) to work around this.
