### ISSUE TITLE
Question: Is the terraform-example-foundation project related to this one?

### ISSUE THREAD

**Issue by victuos** [GoogleCloudPlatform/cloud-foundation-toolkit#924]
Hey everyone, 
we are starting a redesign at our company based on the GCP security foundation pdf provided by Google: https://services.google.com/fh/files/misc/google-cloud-security-foundations-guide.pdf

They have a reference to the https://github.com/terraform-google-modules/terraform-example-foundation project and describe it as a good blueprint.

How does this project compare with the example-foundation? What are the main differences? Are these being developed in cooperation?

**Comment by victuos** [comment]
Motive for this question: I think people might get confused when they try designing their infrastructure and stumble on 2 seperate maintained terraform foundation projects without references to eachother

**Comment by morgante** [comment]
They're the same.

The example foundation is an example of how you can compose the CFT modules together into a foundation, as [explained here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/docs/terraform.md#examples).

**Comment by victuos** [comment]
> They're the same.
> 
> The example foundation is an example of how you can compose the CFT modules together into a foundation, as [explained here](https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/blob/master/docs/terraform.md#examples).

Thanks!
