### ISSUE TITLE
v1.0.0 devtools release failed

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#934]
See https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/runs/2785561332?check_suite_focus=true

**Comment by morgante** [comment]
It looks like the problem is they have dropped terraform-bundle support in v1.0.0: https://github.com/hashicorp/terraform/tree/v1.0.0/tools/terraform-bundle

**Comment by bharathkkb** [comment]
Looks like a good approach maybe to just set `TF_PLUGIN_CACHE_DIR`. Then TF 1.0 should download provider to cache if it does not exist or use the one in cache if it matches.

**Comment by morgante** [comment]
Do we even need the cache functionality still?

**Comment by bharathkkb** [comment]
I added some benchmark stats with new approach in the PR. I think since its low effort and good time improvements for developers in bigger modules we should keep it.

**Comment by morgante** [comment]
Ah, I was thinking we'd have to prepopulate the cache. I agree setting the variable is good so that at least within a test run we can avoid re-downloading. Thanks!
