### ISSUE TITLE
GKE DM template "The reference 'masterAuth.clientKey' is not found"

### ISSUE THREAD

**Issue by gruihuang** [GoogleCloudPlatform/cloud-foundation-toolkit#94]
There would be an error "The reference 'masterAuth.clientKey' is not found" when users do not specify "issueClientCertificate" in config or the value of "issueClientCertificate" is false. That feature actually forces users to enable client certificate, which is not expected.

**Comment by morgante** [comment]
Thanks for the contribution. All new contributions should go to our new GitHub: https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit/tree/master/dm/templates

Could you please file this PR there? Thanks.

**Comment by gruihuang** [comment]
Already solved in repository "https://github.com/GoogleCloudPlatform/cloud-foundation-toolkit"
