### ISSUE TITLE
Feature request to provide an operations suite alert policy template for google deployment manager template

### ISSUE THREAD

**Issue by xalien10** [GoogleCloudPlatform/cloud-foundation-toolkit#940]
Is it possible to provide a google deployment manager template to create alert policies based on google cloud logging metrics? We've seen that stack driver template is able to create alert policy channel notifications for already existing monitoring metrics.
Basically we are in need of a GDM template so that we can manage our alert policies for any specific services within google cloud platform. Any valuable suggestion is preferable.
Thanks in advance
@ocsig

**Comment by morgante** [comment]
We are not currently developing new Deployment Manager templates, as most of our new efforts are focused on Config Connector and Terraform.

**Comment by xalien10** [comment]
So, what do you suggest for IAC? Currently, we're moving forward with GDM for our services. Should we stop using that and use Terraform instead of GDM?

**Comment by morgante** [comment]
I would recommend using either Terraform or Config Connector.

**Comment by xalien10** [comment]
Thank you @morgante for your kind response and suggestions
