### ISSUE TITLE
devtools: terraform fmt linter not working in 1.0

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#955]
It looks like #936 broke the `terraform fmt` linter. When running the linter for the first time, this error is raised:

```
Running terraform fmt
There are some problems with the CLI configuration:
╷
│ Error: The specified plugin cache dir /workspace/test/integration/tmp/.terraform cannot be opened: stat /workspace/test/integration/tmp/.terraform: no such file or directory
│
╵

As a result of the above problems, Terraform may not behave as intended.
```

Note this only happens the *first* time. Once the cache has been built, tests start passing.

**Comment by morgante** [comment]
This seems to happen only intermittently, likely based on what has been cached already. I'm having trouble reproducing, but leaving this open in case others run into it.

@bharathkkb FYI

**Comment by bharathkkb** [comment]
I was also able to repro. Looks like TF does do a check if the dir exists. We can pre create if not exists.
https://github.com/hashicorp/terraform/blob/main/internal/command/cliconfig/cliconfig.go#L277
