### ISSUE TITLE
Install instructions do not provide a working CLI on the Cloud Console.

### ISSUE THREAD

**Issue by Alex-IBMi** [GoogleCloudPlatform/cloud-foundation-toolkit#971]
Related to: "User Guide install instructions do not produce working cft CLI. #603"

I applied the workaround posted on that issue, the cli starts on the venv but then it shows a series of errors:

> (venv) someone@cloudshell:~/cloud-foundation-toolkit/dm (plan9-322111)$ cft --help
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.7/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/someone/cloud-foundation-toolkit/dm/src/cloud_foundation_toolkit/__init__.py", line 15, in <module>
    creds_store.DevShellCredentialProvider(),
AttributeError: module 'googlecloudsdk.core.credentials.store' has no attribute 'DevShellCredentialProvider'

**Comment by morgante** [comment]
@Alex-IBMi We're no longer actively updating the old (Python-based) CLI, so you might want to skip using it.

@ocsig Do you have any ideas for this error?

**Comment by Alex-IBMi** [comment]
Thanks!!! Did not knew that... which version should I use instead?

**Comment by morgante** [comment]
@Alex-IBMi In general, most of our development effort is focused on Terraform or Config Connector. I recommend using one of those instead.

**Comment by Alex-IBMi** [comment]
Thanks a lot!!!
