### ISSUE TITLE
devtools: license header check fails on .hcl files 

### ISSUE THREAD

**Issue by morgante** [GoogleCloudPlatform/cloud-foundation-toolkit#978]
The new license header checker seems to not work on hcl files, as seen here: https://github.com/terraform-google-modules/terraform-google-kubernetes-engine/pull/980

**Comment by bharathkkb** [comment]
I believe [upstream](https://github.com/google/addlicense/blob/5b18a98e808ff5f4db3e0330b7b5dbd3416d3870/main.go#L290) addlicense has support for HCL and we just missed headers on that. Also okay to remove that file since we no longer need that for caching.

**Comment by morgante** [comment]
Oops, I guess I should have checked the file first. Thanks. :)
